sudo: required

services:
  - docker

install:
 - make build

before_script:
 - make test

script:
 - make install

before_deploy:
 - make DOCKER_USER=${DOCKER_USER} DOCKER_PASSWORD=${DOCKER_PASSWORD} login
 - make DOCKER_USER=${DOCKER_GITHUB_USER} DOCKER_PASSWORD=${DOCKER_GITHUB_PASSWORD} DOCKER_REGISTRY_AUTH=docker.pkg.github.com login

deploy:
  provider: script
  script: make deploy
  on:
    branch: master

after_deploy:
 - make logout
