version: '2'

services:
  restic:
    build: .
    environment:
      - RESTIC_REPOSITORY="rclone:remote:server-backup"
      - RESTIC_TAG=latest
      - RESTIC_PASSWORD=test
      - RCLONE_CONFIG=/rclone
      - RCLONE_MEGA_HARD_DELETE=true
      - RCLONE_BWLIMIT=1M
      - RCLONE_VERBOSE=true
      - RCLONE_STDIO=true
    volumes:
      - test_data:/data/test_data
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/rclone.conf:/rclone.conf

volumes:
  test_data:
    external:
      name: test_data