version: '2'

services:
  restic:
    container_name: restic
    image: cobrijani/restic-backup:latest
    environment:
      - RESTIC_REPOSITORY=${RESTIC_REPOSITORY}
      - RESTIC_TAG=${RESTIC_TAG}
      - RESTIC_PASSWORD=${RESTIC_PASSWORD}
      - RESTIC_FORGET_ARGS="--keep-last 5"
    volumes:
      - data-to-backup:/data/data-to-backup

  restic-rclone:
    container_name: restic-rclone
    image: cobrijani/restic-backup:rclone-latest
    environment:
      - RESTIC_REPOSITORY=${RESTIC_REPOSITORY}
      - RESTIC_TAG=${RESTIC_TAG}
      - RESTIC_PASSWORD=${RESTIC_PASSWORD}
      - RCLONE_STDIO=1
      - RCLONE_BWLIMIT=1M
      - RCLONE_MEGA_HARD_DELETE=1
      - RCLONE_VERBOSE=1
      - RCLONE_CONFIG=/rclone.conf
      - RESTIC_FORGET_ARGS="--keep-last 5"
    volumes:
      - data-to-backup:/data/data-to-backup
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/rclone.conf:/rclone.conf

volumes:
  data-to-backup:
    external:
      name: data-to-backup