version: '2'

services:
  restic:
    container_name: restic
    image: restic-backup
    build: .
    environment:
      - RESTIC_REPOSITORY=rclone:remote:server-backup
      - RESTIC_TAG=cobrijani.com
      - RESTIC_PASSWORD=${RESTIC_PASSWORD}
      - RCLONE_STDIO=1
      - RCLONE_BWLIMIT=1M
      - RCLONE_MEGA_HARD_DELETE=1
      - RCLONE_VERBOSE=1
      - RCLONE_CONFIG=/rclone.conf
      - RESTIC_FORGET_ARGS="--keep-last 5"
    volumes:
      - portainer_data:/data/portainer_data
      - gitea_data:/data/gitea_data
      - gitea_postgres:/data/gitea_postgres
      - jenkins_home:/data/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/rclone.conf:/rclone.conf

volumes: 
  portainer_data:
    external:
      name: portainer_data
  gitea_data:
    external:
      name: gitea_data
  gitea_postgres:
    external:
      name: gitea_postgres
  jenkins_home:
    external:
      name: jenkins_home