schemaVersion: '2.0.0'
commandTests:  
  - name: "restic package installation"
    setup: [["/entry.sh"]]
    command: "which"
    args: ["restic"]
    expectedOutput: ["/bin/restic"]
  - name: "rclone package installation"
    setup: [["/entry.sh"]]
    command: "which"
    args: ["rclone"]
    expectedOutput: ["/bin/rclone"]
fileExistenceTests:
- name: 'log directory exists'
  path: '/var/log'
  shouldExist: true
- name: 'cron log file exists'
  path: '/var/log/cron.log'
  shouldExist: true
- name: 'backup script exists'
  path: '/bin/backup'
  shouldExist: true
metadataTest:
  volumes: ["/data"]
  entrypoint: ["/entry.sh"]
  cmd: ["tail","-fn0", "/var/log/cron.log"]