name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build image
      run: make build
    - name: Test image
      run: make test
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry (Normal)
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: docker.pkg.github.com/cobrijani/restic-backup-docker/restic-backup-docker
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.pkg.github.com
    - name: Publish to Registry (Rclone)
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: docker.pkg.github.com/cobrijani/restic-backup-docker/restic-backup-docker-rclone
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.pkg.github.com
        dockerfile: rclone/Dockerfile
