name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build image
      run: make build
    - name: Test image
      run: make test
    - name: Tag image
      run: make install
