name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build image
      run: make build
    - name: Test image
      run: make test
    - name: Tag image
      run: make install
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
#       if: github.ref == 'master'
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: Cobrijani/restic-backup-docker/restic-backup-docker:latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.pkg.github.com
