name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      env:
        ORG_NAME: cobrijani/restic-backup-docker
        REPO_NAME: restic-backup-docker
        RCLONE_REPO_NAME: restic-backup-docker-rclone
        DOCKER_REGISTRY: docker.pkg.github.com
    - uses: actions/checkout@v1
    - name: Build image
      run: make build ORG_NAME=${ORG_NAME} REPO_NAME=${REPO_NAME} RCLONE_REPO_NAME=${RCLONE_REPO_NAME}
    - name: Test image
      run: make test
    - name: Tag image
      run: make install ORG_NAME=${ORG_NAME} REPO_NAME=${REPO_NAME} RCLONE_REPO_NAME=${RCLONE_REPO_NAME} DOCKER_REGISTRY=${DOCKER_REGISTRY}
